### ISSUE TITLE
Add a logger

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/ImageDePHI#112]
https://github.com/Delgan/loguru is a very popular choice and is much easier to configure than the built-in logger.

This task includes replacing all `print` and most `click.echo` calls with a logger call of the appropriate level.

This task should resolve #52 too.

**Comment by marySalvi** [comment]
I've looked into both loggers a bit: 
`loguru` touts being ready out of the box and beginner friendly while the core logger seems to be more versatile with more configuration. Without using either it is hard for me to discern the impact of these claims. 
What seems to be the biggest difference, to me, is that `loguru` has only one logger whereas the core logger has the ability to create multiple loggers. I do not know if this feature would actually affect us though. Also it should be noted that `loguru` is fully compatible with the core logger so it would be possible to use `loguru` for its ease of setup but still leverage the core logger if we need something more complex in the future. 
All of this is to say, I don't have a strong preference either way and would be happy to implement whichever is best for the project.

**Comment by marySalvi** [comment]
Closed by #123
