### ISSUE TITLE
Redact list of images

### ISSUE THREAD

**Issue by marySalvi** [DigitalSlideArchive/ImageDePHI#121]
Allow a user to indicate a list of images to redact instead of the entire directory perhaps something like:

```
imagedephi run [inputpath] --imageList [array of images]
```

**Comment by manthey** [comment]
Would it make more sense to just allow standard globbing and multiple input paths?

**Comment by brianhelba** [comment]
This seems like a duplicate of #101

**Comment by manthey** [comment]
Closed as being covered by #101.
