### ISSUE TITLE
Explore showing macro, label images in UI

### ISSUE THREAD

**Issue by naglepuff** [DigitalSlideArchive/ImageDePHI#138]

**Comment by naglepuff** [comment]
Things to consider:

What size do we want the images?
If macro/label images are very large, should the web server or browser handle scaling to a more reasonable display size?

**Comment by manthey** [comment]
@jtomeck may weigh in on this from a UI perspective.  In other projects, we show label images at ~160 pixels across in lists and around twice that size for detail.  Internally, we've seen label and macro images that are ~4k across, so for larger images scaling on the server is probably better than on the browser (but may not matter that much depending on what we do for paging).
