### ISSUE TITLE
Test redacting metadata with no pointer

### ISSUE THREAD

**Issue by naglepuff** [DigitalSlideArchive/ImageDePHI#146]
Using tools like `libtiff` to set metadata can result in a tiff file where old metadata is still around, but not referenced by a tag. This can be an issue if a user uses `tiffset` to change metadata that contained PHI.

We should add a test to ImageDePHI that demonstrates that we would sanitize such data. 

In order to effectively test we would need to use `tiffset` on a file to add a new piece of metadata to an image, confirm that the old value and new value are both contained somewhere in the file, and then show that only the new value is in the file after being run through ImageDePHI.

**Comment by manthey** [comment]
Yes.  I'd take a small tiff file (such as https://github.com/girder/large_image/blob/master/test/test_files/small_la.tiff -- renamed to small.tiff for this example) and add some metadata `tifftools set -y small.tiff --set ImageDescription 'Secret Message'`, then change it with `tiffset`: `tiffset -s 270 'Public Message' small.tiff`.  `grep Secret small.tiff` will match.  

I've attached small.tiff so you can skip those steps.
[small.zip](https://github.com/DigitalSlideArchive/ImageDePHI/files/12338432/small.zip)
