### ISSUE TITLE
Strict redaction - define minimum required meta

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/ImageDePHI#165]
Define the minimum required metadata necessary to load .svs. This will allow users to appy a "strict" redaction profile without requiring the institution to inspect a bunch of tags. Start with .svs since the viewers and dataloaders are more mature.

**Comment by manthey** [comment]
This could be done by having a struct ruleset with a fallback rule for unknown tags/images which removes those tags/images.  We'd have to add a fallback rule.

**Comment by naglepuff** [comment]
I've been doing some reading of the tiff standard to try and figure out how to determine what the minimum tag set would be. A good starting point would be the baseline tiff plus any tiff extensions commonly used by whole slide images. I'm not sure what those would be, however.

I imagine that the "Tiled Images" tag set should definitely be included, but the others are unclear.

I believe this screenshot captures all of the tiff extensions defined by Tiff 6.0. Which ones should be included in the minimum tagset for this sort of redaction?

![image](https://github.com/DigitalSlideArchive/ImageDePHI/assets/7085625/bee83baf-f03d-4d76-a6e5-bdf13b79352a)

**Comment by manthey** [comment]
The required fields are
![image](https://github.com/DigitalSlideArchive/ImageDePHI/assets/8781639/d5427c9b-5fc4-4f2b-a6a8-ddee52540808)
plus 254, 266, 274, 317, 320, 322, 323, 324, 325, 330, 338, 339, 346, 347, 512-531, 559, 34675
