### ISSUE TITLE
command line option documentation

### ISSUE THREAD

**Issue by dgutman** [DigitalSlideArchive/ImageDePHI#169]
Since in most cases people will want to "run" deid, I think it would be useful to specify the -o output flag if you run ./imagedephi with no options or with --help.  I had to do then do ./imagedephi run --help

Probably useful to have this output most common use case in the initial -v or if you just run ./imagedephi.

**Comment by manthey** [comment]
If there is a way in click to add command examples when no subcommand is given, that would help.

**Comment by manthey** [comment]
Added in #271
