### ISSUE TITLE
Command line output

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/ImageDePHI#181]
I'd like to have a command line output option where it would print how many images are being redacted and the simple progress (e.g.,
"Redacting 1/25: <name>, 0.00% done"
"Redacting 2/25: <name>, 4.00% done"
).  That percent done would ideally be based on the size of the input files, not the file count. 

Currently, the run command is silent unless we add `-v`, at which point it is noisy.  I'm looking for an informative middle ground.

**Comment by naglepuff** [comment]
Closing in favor of #216
