### ISSUE TITLE
Windows executable package has wrong extension

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/ImageDePHI#191]
We upload a tar file as `Windows-imagedephi-cli.zip`. But, Windows won't open it because it is NOT a zip file.  @zachmullen, do you know why we are creating a tar file and calling it a zip?

I think we should be creating a zip file.

**Comment by zachmullen** [comment]
Hm, it's definitely a tar:

```python
In [9]: with open('/Users/zach/Downloads/Windows-imagedephi-cli.zip', 'rb') as fd:
   ...:     fd.seek(257)  # tar offset
   ...:     print(fd.read(8))
   ...: 
b'ustar  \x00'
```

I'll put in a fix.

**Comment by zachmullen** [comment]
I'm remembering the history of this now. Windows, at least on the GitHub Actions runner, does not have a `zip` executable available, but does have `tar.exe`, but I failed to change the file name on windows. If we want a zip on Windows, I can try to use the `compact.exe` command instead.

**Comment by manthey** [comment]
It'd be better to have a zip.  I don't expect some windows users to know what to do with a tar file, but windows has zip support out of the box.

**Comment by zachmullen** [comment]
The powershell command on #192 seems to work (I used the artifact upload command of GH actions to upload it): https://github.com/DigitalSlideArchive/ImageDePHI/actions/runs/7980246174
