### ISSUE TITLE
Provide Feedback During DeID CLI process

### ISSUE THREAD

**Issue by dgutman** [DigitalSlideArchive/ImageDePHI#216]
Would be useful to have some sort of TQDM type output at the folder and/or file level.  I was de-identifying about 170 images (400 GB) and it seems to be chugging along, but I have no simple way to figure out if it's working or crashed.  Using some linux tricks I can tell it's working ( du -ch  / etc..) but for a less technical user, they wouldn't have any way to figure out what's going on.

![image](https://github.com/DigitalSlideArchive/ImageDePHI/assets/713166/a4e1efe9-aaa0-414e-892c-73f9d2c4d81e)

**Comment by naglepuff** [comment]
Currently there's a click progress bar (implemented in #164) being used by the main redaction loop that apparently logs progress to a file, not the command line. This change was called "quick and dirty" in that PR so I'd like to talk with @marySalvi about what parts of that (if any) are still needed and what exactly its doing, and then perhaps update logging to be more friendly for CLI users. That should be possible next week.
