### ISSUE TITLE
Handle existing file in output

### ISSUE THREAD

**Issue by marySalvi** [DigitalSlideArchive/ImageDePHI#48]
Currently if you run redaction on an image and it already exists in the output directory it fails silently. First pass could just be informing the user that it failed but would probably be ideal to give the user options of renaming, overwriting or canceling.

**Comment by naglepuff** [comment]
It would be useful to keep our options open by adding a flag to the CLI (--overwrite). By default we could just report which images already exist and skip redaction for those images. Running with the overwrite flag would overwrite the existing output files. Tifftools has a flag for this.

**Comment by brianhelba** [comment]
I think it helps to define what problems the no-overwrite option is trying to solve. IMO, the worst case would be that if we always overwrite, a user could select an output directory with existing files named `REDACTED_...` and accidentally overwrite their valuable content. Is that a real problem?

Are users going to have existing files named exactly as `REDACTED_...` which are created by any tool other than ImageDePHI? I doubt it.

Would it be that bad if the prior file content was lost? If we're re-running with the same or improved redaction rules, overwriting will by a no-op or reflect the intent of the user. If the user wanted to also preserve the prior files and this was a mistake, can't they just re-run ImageDePHI to deterministically re-generate them?

I don't think we can save users from every mistake they make. Introducing too many guardrails will at best increase the complexity of the tool. At worst, it will cause [alarm fatigue](https://en.wikipedia.org/wiki/Alarm_fatigue), training users to blindly click through warnings without reading them.
