### ISSUE TITLE
CLI syntax

### ISSUE THREAD

**Issue by alexbaras** [DigitalSlideArchive/ImageDePHI#54]
I am not sure but could someone please check if the instruction for command line are correct? I do not see a imagedephi.py file.

python imagedephi.py <directory of input images> <directory to store redacted images>

**Comment by brianhelba** [comment]
This is resolved by the updated https://github.com/DigitalSlideArchive/ImageDePHI/blob/main/README.md documentation.

Thanks for the report @alexbaras!
