### ISSUE TITLE
Ctrl-C causes exception dump when running binary

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/ImageDePHI#67]
See:
* https://pyinstaller.org/en/stable/feature-notes.html#onefile-mode-and-temporary-directory-cleanup

Note, the handling of `KeyboardInterrupt` by `asyncio.run` is improved in Python 3.11:
* https://docs.python.org/3/library/asyncio-runner.html#id3
* https://github.com/python/cpython/pull/32105

**Comment by manthey** [comment]
This was resolved at some point in the past.
