### ISSUE TITLE
Linux executable fails

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/ImageDePHI#83]
On Ubuntu 20.04, I get the following error from the linux executable artifact produced when #78 was merged to main (https://github.com/DigitalSlideArchive/ImageDePHI/suites/11925106988/artifacts/624663293):

```
[3525354] Error loading Python lib '/tmp/_MEI8E6ATO/libpython3.10.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEI8E6ATO/libpython3.10.so.1.0)
```

This happens identically on two Ubuntu 20.04 systems, both of which have python 3.10 locally.

**Comment by brianhelba** [comment]
This is the problem: https://pyinstaller.org/en/stable/usage.html#making-gnu-linux-apps-forward-compatible

The solution is to use a CI runner which is an earlier version of Ubuntu. Alternatively, we could run the build inside Docker on Linux with an older image.

**Comment by brianhelba** [comment]
GitHub Actions only offers Ubuntu 20.04 at the earliest: https://github.com/actions/runner-images/#available-images

Do we need to support 18.04?
